[project]
name = "agora"
version = "0.1.0"
description = "Synthetic Agora - A framework for simulating social media dynamics with AI agents"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "pytest>=8.4.1",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.43",
]
